name: CI/CD Pipeline

on:
  push:
    branches:
      - 0.1-develop
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'
      
      - name: Build
        run: |
          cd simple-go-web-server
          go build -o go-app .

      - name: Build Docker image
        run: |
          docker build -t go-docker-image:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push go-docker-image:latest

      - name: Set up Kubernetes Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name go-cluster --region us-east-1

      - name: Deploy to Kubernetes with Helm
        if: github.ref == 'refs/heads/prod'
        run: |
          helm upgrade --install go-release-chart ./helm-chart --set image.tag=latest

      - name: Notify Development
        if: github.ref == 'refs/heads/0.1-develop'
        run: echo "Deploying to development environment..."
